"""initial saas schema

Revision ID: 297962752bc2
Revises: 
Create Date: 2026-09-29 00:22:12.181463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297962752bc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_outcomes',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('next_close', sa.Float(), nullable=True),
    sa.Column('next_ret_pct', sa.Float(), nullable=True),
    sa.Column('direction_correct', sa.Integer(), nullable=False),
    sa.Column('hit_tp1', sa.Integer(), nullable=False),
    sa.Column('hit_sl', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_paper_outcomes_signal_id'), 'paper_outcomes', ['signal_id'], unique=False)
    op.create_table('paper_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.String(length=40), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('tp1', sa.Float(), nullable=True),
    sa.Column('tp2', sa.Float(), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('conviction_pct', sa.Float(), nullable=True),
    sa.Column('prob_up', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('position_size_pct', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ticker', name='uq_paper_date_ticker')
    )
    op.create_index(op.f('ix_paper_signals_ticker'), 'paper_signals', ['ticker'], unique=False)
    op.create_index(op.f('ix_paper_signals_trade_date'), 'paper_signals', ['trade_date'], unique=False)
    op.create_table('signal_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('signal', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('prob_up', sa.Float(), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('conviction_pct', sa.Float(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('tp1', sa.Float(), nullable=True),
    sa.Column('tp2', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('position_size_pct', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=16), nullable=True),
    sa.Column('trading_allowed', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('universe', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uq_signal_ticker_date')
    )
    op.create_index(op.f('ix_signal_cache_ticker'), 'signal_cache', ['ticker'], unique=False)
    op.create_index(op.f('ix_signal_cache_trade_date'), 'signal_cache', ['trade_date'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tickers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_signal_cache_trade_date'), table_name='signal_cache')
    op.drop_index(op.f('ix_signal_cache_ticker'), table_name='signal_cache')
    op.drop_table('signal_cache')
    op.drop_index(op.f('ix_paper_signals_trade_date'), table_name='paper_signals')
    op.drop_index(op.f('ix_paper_signals_ticker'), table_name='paper_signals')
    op.drop_table('paper_signals')
    op.drop_index(op.f('ix_paper_outcomes_signal_id'), table_name='paper_outcomes')
    op.drop_table('paper_outcomes')
    # ### end Alembic commands ###
